import { Inter } from 'next/font/google'

import type { Metadata } from 'next'

import Providers from '@/components/Providers'

import { cn } from '@/libs/utils'
import '@/styles/index.css'

const inter = Inter({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn('relative h-full font-sans antialiased', inter.className)}
      >
        <main className="relative flex min-h-screen flex-col">
          <Providers>
            <nav>네비게이션 바</nav>
            <div className="flex-1 flex-grow">{children}</div>
          </Providers>
        </main>
      </body>
    </html>
  )
}
